export const STAFF_LIST_REQUEST = 'STAFF_LIST_REQUEST';
export const STAFF_LIST_SUCCESS = 'STAFF_LIST_SUCCESS';
export const STAFF_LIST_FAIL = 'STAFF_LIST_FAIL';

export const STAFF_DETAILS_REQUEST = 'STAFF_DETAILS_REQUEST';
export const STAFF_DETAILS_SUCCESS = 'STAFF_DETAILS_SUCCESS';
export const STAFF_DETAILS_FAIL = 'STAFF_DETAILS_FAIL';
